prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/ventas_png.sql
@@application/shared_components/files/beneficio_financiero_1_png.sql
@@application/shared_components/files/cliente_png.sql
@@application/shared_components/files/tienda_online_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/authorizations/auth_page_by_priv.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/caja_conf_descripcion.sql
@@application/shared_components/user_interface/lovs/categorias_productos_nombre.sql
@@application/shared_components/user_interface/lovs/ciudades_descripcion.sql
@@application/shared_components/user_interface/lovs/clientes_codigo_usuario.sql
@@application/shared_components/user_interface/lovs/componentes.sql
@@application/shared_components/user_interface/lovs/comprobantes_nro_comprobante.sql
@@application/shared_components/user_interface/lovs/cuentas_cobrar_estado.sql
@@application/shared_components/user_interface/lovs/departamentos_descripcion.sql
@@application/shared_components/user_interface/lovs/departamentos_descripcion_002.sql
@@application/shared_components/user_interface/lovs/documentos_descripcion.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/empleados_codigo_usuario.sql
@@application/shared_components/user_interface/lovs/empleados_nombre.sql
@@application/shared_components/user_interface/lovs/genero_personas.sql
@@application/shared_components/user_interface/lovs/lov_personas_clientes.sql
@@application/shared_components/user_interface/lovs/marcas_nombre.sql
@@application/shared_components/user_interface/lovs/moneda_descripcion.sql
@@application/shared_components/user_interface/lovs/nro_documento_no_cliente.sql
@@application/shared_components/user_interface/lovs/nro_documento_no_empleado.sql
@@application/shared_components/user_interface/lovs/oficinas_descripcion.sql
@@application/shared_components/user_interface/lovs/orden_compra_estado.sql
@@application/shared_components/user_interface/lovs/ordenes_compra_observacion.sql
@@application/shared_components/user_interface/lovs/ordenes_venta_estado.sql
@@application/shared_components/user_interface/lovs/paginas.sql
@@application/shared_components/user_interface/lovs/paises_descripcion.sql
@@application/shared_components/user_interface/lovs/persona_nombre.sql
@@application/shared_components/user_interface/lovs/personas_estado_civil.sql
@@application/shared_components/user_interface/lovs/personas_nro_documento.sql
@@application/shared_components/user_interface/lovs/personas_nro_documento_1.sql
@@application/shared_components/user_interface/lovs/personas_tipo_personas.sql
@@application/shared_components/user_interface/lovs/privilegios.sql
@@application/shared_components/user_interface/lovs/privilegios_codigo.sql
@@application/shared_components/user_interface/lovs/productos_nombre.sql
@@application/shared_components/user_interface/lovs/productos_proveedor_precio.sql
@@application/shared_components/user_interface/lovs/proveedores_codigo_usuario.sql
@@application/shared_components/user_interface/lovs/proveedores_nombre.sql
@@application/shared_components/user_interface/lovs/roles_descripcion.sql
@@application/shared_components/user_interface/lovs/talonarios_tipo_comprobante.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/custom_login.sql
@@application/shared_components/plugins/template_component/theme_42_kebe_dashboard.sql
@@application/shared_components/plugins/template_component/kebe_dashboard.sql
@@application/shared_components/plugins/dynamic_action/bbe_sweet_alert.sql
@@application/shared_components/plugins/region_type/orclking_bootstrap_carousel_extension.sql
@@application/shared_components/plugins/dynamic_action/print_region_to_pdf_v_2_0.sql
@@application/shared_components/plugins/template_component/multi_purpose_card.sql
@@application/shared_components/plugins/dynamic_action/apex_notification.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00110.sql
@@application/pages/page_00112.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
