-- ============================================================================
-- F24.1 - Orden de Pago (tablas + procedimientos)
-- ============================================================================
-- H2 del PLAN_CUENTAS_PAGAR.md. Modelo de DOS PASOS (decision PO 2026-07-02):
--   Paso 1  PRC_GENERAR_ORDEN_PAGO  -> emite la OP en BORRADOR (documento de
--           autorizacion; NO baja saldo). Aplica montos a una o varias CxP.
--   Paso 2  PRC_CONFIRMAR_ORDEN_PAGO -> ejecuta el pago: baja el SALDO de cada CxP
--           aplicada, la marca PAGADA/PARCIAL y la OP pasa a PAGADA.
--           SIN impacto en caja (fuera de alcance F24).
--           PRC_ANULAR_ORDEN_PAGO   -> anula una OP en BORRADOR (la reversa de una
--           OP ya PAGADA queda fuera de alcance).
--
-- Reusa la secuencia huerfana SEQ_ORDEN_PAGO_ID (scaffold que ya existia).
--
-- Rango de error: -20935 arg/monto invalido, -20936 CxP no corresponde al
--   proveedor, -20937 estado de OP invalido (no BORRADOR) al confirmar, -20938
--   saldo insuficiente al confirmar, -20939 no se puede anular / verificacion.
--
-- Los procedimientos NO hacen COMMIT: la transaccion la cierra el proceso APEX
-- que los invoca (o el smoke test con ROLLBACK).
--
-- Idempotente: tablas con IF NOT EXISTS; CREATE OR REPLACE para los procs.
-- Pre-requisitos: CUENTAS_PAGAR (F24 H1), PROVEEDORES, METODOS_PAGO, FN_AHORA,
--                 SEQ_ORDEN_PAGO_ID.
--
-- Conexion: SQLCL_CONNECTION=tesis_db
-- Ejecucion (esta maquina): sql -S -name tesis_db < db/F24_1_ordenes_pago.sql
-- ============================================================================

ALTER SESSION SET CURRENT_SCHEMA = WKSP_WORKPLACE;

set serveroutput on size unlimited
set define off
whenever sqlerror exit sql.sqlcode rollback

prompt == F24.1.0 Pre-check ==
DECLARE
  v_cnt PLS_INTEGER;
  PROCEDURE need(p_name VARCHAR2, p_type VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM all_objects
     WHERE owner='WKSP_WORKPLACE' AND object_name=p_name AND object_type=p_type
       AND status='VALID';
    IF v_cnt = 0 THEN
      RAISE_APPLICATION_ERROR(-20935,'Falta '||p_type||' '||p_name||' (aplicar F24 H1/F19 antes).');
    END IF;
  END;
BEGIN
  need('CUENTAS_PAGAR','TABLE');
  need('PROVEEDORES','TABLE');
  need('METODOS_PAGO','TABLE');
  need('FN_AHORA','FUNCTION');
  SELECT COUNT(*) INTO v_cnt FROM all_sequences
   WHERE sequence_owner='WKSP_WORKPLACE' AND sequence_name='SEQ_ORDEN_PAGO_ID';
  IF v_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20935,'Falta la secuencia SEQ_ORDEN_PAGO_ID.');
  END IF;
  -- Chequeo H1: la columna FECHA_VENCIMIENTO debe existir.
  SELECT COUNT(*) INTO v_cnt FROM all_tab_columns
   WHERE owner='WKSP_WORKPLACE' AND table_name='CUENTAS_PAGAR' AND column_name='FECHA_VENCIMIENTO';
  IF v_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20935,'Falta CUENTAS_PAGAR.FECHA_VENCIMIENTO (aplicar F24 H1).');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  = Pre-check OK');
END;
/

prompt == F24.1.1 Tabla ORDENES_PAGO ==
DECLARE
  v_cnt PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM all_tables
   WHERE owner='WKSP_WORKPLACE' AND table_name='ORDENES_PAGO';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE WKSP_WORKPLACE.ORDENES_PAGO (
        ID_ORDEN_PAGO  NUMBER DEFAULT WKSP_WORKPLACE.SEQ_ORDEN_PAGO_ID.NEXTVAL
                         CONSTRAINT PK_ORDENES_PAGO PRIMARY KEY,
        ID_PROVEEDOR   NUMBER NOT NULL
                         CONSTRAINT FK_OP_PROVEEDOR
                         REFERENCES WKSP_WORKPLACE.PROVEEDORES (ID_PERSONA),
        FECHA_EMISION  DATE,
        FECHA_PAGO     DATE,
        TOTAL_PAGO     NUMBER,
        ID_METODO_PAGO NUMBER
                         CONSTRAINT FK_OP_METODO
                         REFERENCES WKSP_WORKPLACE.METODOS_PAGO (ID_METODO_PAGO),
        ESTADO         VARCHAR2(20) DEFAULT 'BORRADOR'
                         CONSTRAINT CK_OP_ESTADO
                         CHECK (ESTADO IN ('BORRADOR','PAGADA','ANULADA')),
        USUARIO        VARCHAR2(60),
        OBSERVACION    VARCHAR2(255),
        MOTIVO_ANULACION VARCHAR2(255)
      )]';
    DBMS_OUTPUT.PUT_LINE('  + ORDENES_PAGO creada');
  ELSE
    DBMS_OUTPUT.PUT_LINE('  = ORDENES_PAGO ya existe');
  END IF;
END;
/

prompt == F24.1.2 Tabla ORDEN_PAGO_DET ==
DECLARE
  v_cnt PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM all_tables
   WHERE owner='WKSP_WORKPLACE' AND table_name='ORDEN_PAGO_DET';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE WKSP_WORKPLACE.ORDEN_PAGO_DET (
        ID_DETALLE     NUMBER GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT PK_ORDEN_PAGO_DET PRIMARY KEY,
        ID_ORDEN_PAGO  NUMBER NOT NULL
                         CONSTRAINT FK_OPD_ORDEN
                         REFERENCES WKSP_WORKPLACE.ORDENES_PAGO (ID_ORDEN_PAGO)
                         ON DELETE CASCADE,
        ID_CXP         NUMBER NOT NULL
                         CONSTRAINT FK_OPD_CXP
                         REFERENCES WKSP_WORKPLACE.CUENTAS_PAGAR (ID_CXP),
        MONTO_APLICADO NUMBER NOT NULL
                         CONSTRAINT CK_OPD_MONTO CHECK (MONTO_APLICADO > 0)
      )]';
    DBMS_OUTPUT.PUT_LINE('  + ORDEN_PAGO_DET creada');
  ELSE
    DBMS_OUTPUT.PUT_LINE('  = ORDEN_PAGO_DET ya existe');
  END IF;
END;
/

prompt == F24.1.2b Columna MOTIVO_ANULACION (idempotente, para tablas ya creadas) ==
DECLARE
  v_cnt PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM all_tab_columns
   WHERE owner='WKSP_WORKPLACE' AND table_name='ORDENES_PAGO' AND column_name='MOTIVO_ANULACION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WKSP_WORKPLACE.ORDENES_PAGO ADD (MOTIVO_ANULACION VARCHAR2(255))';
    DBMS_OUTPUT.PUT_LINE('  + ORDENES_PAGO.MOTIVO_ANULACION agregada');
  ELSE
    DBMS_OUTPUT.PUT_LINE('  = ORDENES_PAGO.MOTIVO_ANULACION ya existe');
  END IF;
END;
/

prompt == F24.1.3 PRC_GENERAR_ORDEN_PAGO (paso 1: emite BORRADOR, no baja saldo) ==
CREATE OR REPLACE PROCEDURE WKSP_WORKPLACE.PRC_GENERAR_ORDEN_PAGO (
  p_id_proveedor  IN  NUMBER,
  p_ids_cxp       IN  SYS.ODCINUMBERLIST,
  p_montos        IN  SYS.ODCINUMBERLIST,
  p_observacion   IN  VARCHAR2 DEFAULT NULL,
  p_usuario       IN  VARCHAR2 DEFAULT NULL,
  p_id_orden_pago OUT NUMBER
) AS
  v_total NUMBER := 0;
  v_saldo NUMBER;
  v_cnt   PLS_INTEGER;
BEGIN
  IF p_id_proveedor IS NULL THEN
    RAISE_APPLICATION_ERROR(-20935,'Falta el proveedor.');
  END IF;
  IF p_ids_cxp IS NULL OR p_ids_cxp.COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20935,'No hay cuentas por pagar seleccionadas.');
  END IF;
  IF p_montos IS NULL OR p_montos.COUNT <> p_ids_cxp.COUNT THEN
    RAISE_APPLICATION_ERROR(-20935,'La cantidad de montos no coincide con las cuentas.');
  END IF;

  SELECT COUNT(*) INTO v_cnt FROM WKSP_WORKPLACE.PROVEEDORES
   WHERE ID_PERSONA = p_id_proveedor;
  IF v_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20935,'Proveedor inexistente: '||p_id_proveedor);
  END IF;

  -- Cabecera BORRADOR: autoriza, NO baja saldo (paso 1 del modelo de dos pasos).
  INSERT INTO WKSP_WORKPLACE.ORDENES_PAGO (
    ID_PROVEEDOR, FECHA_EMISION, ESTADO, USUARIO, OBSERVACION
  ) VALUES (
    p_id_proveedor, WKSP_WORKPLACE.FN_AHORA, 'BORRADOR',
    NVL(p_usuario, USER), p_observacion
  ) RETURNING ID_ORDEN_PAGO INTO p_id_orden_pago;

  FOR i IN 1 .. p_ids_cxp.COUNT LOOP
    IF p_montos(i) IS NULL OR p_montos(i) <= 0 THEN
      RAISE_APPLICATION_ERROR(-20935,'Monto invalido para la CxP '||p_ids_cxp(i)||'.');
    END IF;
    -- La CxP debe existir, ser del proveedor y seguir pendiente/parcial.
    BEGIN
      SELECT SALDO INTO v_saldo
        FROM WKSP_WORKPLACE.CUENTAS_PAGAR
       WHERE ID_CXP = p_ids_cxp(i)
         AND ID_PROVEEDOR = p_id_proveedor
         AND ESTADO NOT IN ('PAGADA','ANULADA');
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20936,'La CxP '||p_ids_cxp(i)||
        ' no corresponde al proveedor o no esta pendiente.');
    END;
    IF p_montos(i) > v_saldo THEN
      RAISE_APPLICATION_ERROR(-20935,'El monto '||p_montos(i)||' supera el saldo '||
        v_saldo||' de la CxP '||p_ids_cxp(i)||'.');
    END IF;

    INSERT INTO WKSP_WORKPLACE.ORDEN_PAGO_DET (ID_ORDEN_PAGO, ID_CXP, MONTO_APLICADO)
    VALUES (p_id_orden_pago, p_ids_cxp(i), p_montos(i));

    v_total := v_total + p_montos(i);
  END LOOP;

  UPDATE WKSP_WORKPLACE.ORDENES_PAGO
     SET TOTAL_PAGO = v_total
   WHERE ID_ORDEN_PAGO = p_id_orden_pago;
END PRC_GENERAR_ORDEN_PAGO;
/
show errors procedure PRC_GENERAR_ORDEN_PAGO

prompt == F24.1.4 PRC_CONFIRMAR_ORDEN_PAGO (paso 2: ejecuta el pago, baja saldo) ==
CREATE OR REPLACE PROCEDURE WKSP_WORKPLACE.PRC_CONFIRMAR_ORDEN_PAGO (
  p_id_orden_pago  IN NUMBER,
  p_id_metodo_pago IN NUMBER DEFAULT NULL
) AS
  v_estado VARCHAR2(20);
  v_saldo  NUMBER;
  v_nuevo  NUMBER;
  v_cnt    PLS_INTEGER;
BEGIN
  -- Bloquea la cabecera y valida el estado.
  BEGIN
    SELECT ESTADO INTO v_estado FROM WKSP_WORKPLACE.ORDENES_PAGO
     WHERE ID_ORDEN_PAGO = p_id_orden_pago FOR UPDATE;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20937,'Orden de pago inexistente: '||p_id_orden_pago);
  END;
  IF v_estado <> 'BORRADOR' THEN
    RAISE_APPLICATION_ERROR(-20937,'Solo se confirma una OP en BORRADOR (estado actual: '||v_estado||').');
  END IF;

  IF p_id_metodo_pago IS NOT NULL THEN
    SELECT COUNT(*) INTO v_cnt FROM WKSP_WORKPLACE.METODOS_PAGO
     WHERE ID_METODO_PAGO = p_id_metodo_pago;
    IF v_cnt = 0 THEN
      RAISE_APPLICATION_ERROR(-20935,'Metodo de pago invalido: '||p_id_metodo_pago);
    END IF;
  END IF;

  -- Aplica cada detalle: bloquea la CxP, revalida saldo (concurrencia) y lo baja.
  FOR r IN (SELECT ID_CXP, MONTO_APLICADO FROM WKSP_WORKPLACE.ORDEN_PAGO_DET
             WHERE ID_ORDEN_PAGO = p_id_orden_pago) LOOP
    SELECT SALDO INTO v_saldo FROM WKSP_WORKPLACE.CUENTAS_PAGAR
     WHERE ID_CXP = r.ID_CXP FOR UPDATE;
    IF r.MONTO_APLICADO > v_saldo THEN
      RAISE_APPLICATION_ERROR(-20938,'Saldo insuficiente en la CxP '||r.ID_CXP||
        ' (saldo '||v_saldo||', aplica '||r.MONTO_APLICADO||').');
    END IF;
    v_nuevo := v_saldo - r.MONTO_APLICADO;
    UPDATE WKSP_WORKPLACE.CUENTAS_PAGAR
       SET SALDO  = v_nuevo,
           ESTADO = CASE WHEN v_nuevo <= 0 THEN 'PAGADA' ELSE 'PARCIAL' END
     WHERE ID_CXP = r.ID_CXP;
  END LOOP;

  UPDATE WKSP_WORKPLACE.ORDENES_PAGO
     SET ESTADO = 'PAGADA',
         FECHA_PAGO = WKSP_WORKPLACE.FN_AHORA,
         ID_METODO_PAGO = p_id_metodo_pago
   WHERE ID_ORDEN_PAGO = p_id_orden_pago;
END PRC_CONFIRMAR_ORDEN_PAGO;
/
show errors procedure PRC_CONFIRMAR_ORDEN_PAGO

prompt == F24.1.5 PRC_ANULAR_ORDEN_PAGO (solo BORRADOR) ==
CREATE OR REPLACE PROCEDURE WKSP_WORKPLACE.PRC_ANULAR_ORDEN_PAGO (
  p_id_orden_pago IN NUMBER,
  p_motivo        IN VARCHAR2 DEFAULT NULL
) AS
  v_estado VARCHAR2(20);
BEGIN
  BEGIN
    SELECT ESTADO INTO v_estado FROM WKSP_WORKPLACE.ORDENES_PAGO
     WHERE ID_ORDEN_PAGO = p_id_orden_pago FOR UPDATE;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20939,'Orden de pago inexistente: '||p_id_orden_pago);
  END;
  IF v_estado <> 'BORRADOR' THEN
    RAISE_APPLICATION_ERROR(-20939,'Solo se anula una OP en BORRADOR (estado actual: '||
      v_estado||'). Reversar una OP pagada esta fuera de alcance.');
  END IF;
  UPDATE WKSP_WORKPLACE.ORDENES_PAGO
     SET ESTADO = 'ANULADA', MOTIVO_ANULACION = p_motivo
   WHERE ID_ORDEN_PAGO = p_id_orden_pago;
END PRC_ANULAR_ORDEN_PAGO;
/
show errors procedure PRC_ANULAR_ORDEN_PAGO

prompt == F24.1.6 Verificacion final ==
DECLARE
  v_cnt PLS_INTEGER;
  v_ok  BOOLEAN := TRUE;
  PROCEDURE chk(p_name VARCHAR2, p_type VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM all_objects
     WHERE owner='WKSP_WORKPLACE' AND object_name=p_name AND object_type=p_type
       AND status='VALID';
    IF v_cnt>=1 THEN DBMS_OUTPUT.PUT_LINE('  OK  '||RPAD(p_type,9)||p_name);
    ELSE DBMS_OUTPUT.PUT_LINE('  FAIL '||RPAD(p_type,9)||p_name); v_ok:=FALSE; END IF;
  END;
BEGIN
  chk('ORDENES_PAGO','TABLE');
  chk('ORDEN_PAGO_DET','TABLE');
  chk('PRC_GENERAR_ORDEN_PAGO','PROCEDURE');
  chk('PRC_CONFIRMAR_ORDEN_PAGO','PROCEDURE');
  chk('PRC_ANULAR_ORDEN_PAGO','PROCEDURE');
  IF v_ok THEN DBMS_OUTPUT.PUT_LINE(CHR(10)||'F24.1 (OP tablas + procs) aplicado OK.');
  ELSE RAISE_APPLICATION_ERROR(-20939,'F24.1 verificacion FAIL.'); END IF;
END;
/

prompt == F24.1 - fin ==
set define on
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;
